### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Tokoyami** [Footsiefat/openheimer#9]
After I run make and execute ./openheimer it says "Segmentation fault (core dumped)"

**Comment by Tokoyami** [comment]
Full log:
root@NullBoat:/mnt/e/openheimer-master# ./openheimer
Total IP's: 8280
Total threads: 800
IP's per thread: 10
Segmentation fault (core dumped)

**Comment by Footsiefat** [comment]
Unfortunately I am not able to provide full support for this due to this project being a steaming pile of shite held together with duct tape.

I would recommend to debug this using gdb and look at traceback so we can at least figure out where it breaks. :+1:
